name: Deploy Angular to Vercel

on:
  push:
    branches:
      - master  # O la rama que desees usar para despliegues

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Usa la versión de Node.js compatible con Angular 17

      - name: Install dependencies
        run: npm install

      - name: Build Angular project
        run: npm run build --prod

      - name: Deploy to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: npx vercel deploy --prod --token ${{ secrets.VERCEL_TOKEN }} --confirm --cwd dist/frontend-sgap
